CREATE TABLE package_cache_ttl (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_name text NOT NULL,
  last_fetched_at timestamptz NULL
);

CREATE UNIQUE INDEX idx_package_cache_ttl_package_name ON package_cache_ttl (package_name);
