CREATE TABLE package (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  description text,
  keywords jsonb,
  homepage text,
  version text,
  version_normalized text,
  license jsonb,
  source_url text,
  source_type text,
  source_reference text,
  dist_url text,
  dist_type text,
  dist_reference text,
  dist_shasum text,
  type text,
  support_issues text,
  support_source text,
  time text,
  extra jsonb,
  created_at timestamptz NULL,
  updated_at timestamptz NULL,
  funding jsonb,
  autoload jsonb,
  suggest jsonb
);

CREATE UNIQUE INDEX idx_package_name_version ON package (name, version);
CREATE INDEX idx_package_name ON package (name);

CREATE TABLE author (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  homepage text,
  package_id bigint NOT NULL REFERENCES package (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX author_name_email_package_id_unique ON author (name, email, package_id);
CREATE INDEX author_package_id_index ON author (package_id);

CREATE TABLE "require" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  version text NOT NULL,
  package_id bigint NOT NULL REFERENCES package (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NULL,
  updated_at timestamptz NULL
);

CREATE UNIQUE INDEX require_name_version_package_id_unique ON "require" (name, version, package_id);
CREATE INDEX require_package_id_index ON "require" (package_id);

CREATE TABLE require_dev (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  version text NOT NULL,
  package_id bigint NOT NULL REFERENCES package (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NULL,
  updated_at timestamptz NULL
);

CREATE UNIQUE INDEX require_dev_name_version_package_id_unique ON require_dev (name, version, package_id);
CREATE INDEX require_dev_package_id_index ON require_dev (package_id);
